apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: producten-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: producten-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 40