apiVersion: v1
kind: Service
metadata:
  name: producten-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"

spec:
  type: LoadBalancer
  selector:
    app: producten
    release: stable
  ports:
    - port: 8081
      targetPort: 8080